alter table CharacterBackground_focuses drop foreign key FK_gwyci7jpuwu0q3mucbf5q5rjq;
alter table CharacterSkill_focuses drop foreign key FK_m55thyly94po4rbmw03iay1u8;
alter table Player drop foreign key FK_ks4oof9guph2qvo7v6cqdiefx;
alter table PlayerCharacter drop foreign key FK_1wbxymbhm40bq5goo5laqy756;
alter table PlayerCharacter drop foreign key FK_2tvilr6gkaifhe9fei568ij7b;
alter table PlayerCharacter_TraitChanges drop foreign key FK_s5e9fv5uoth36s44agn30vqtt;
alter table PlayerCharacter_TraitChanges drop foreign key FK_ebyhdsyremvpge52v5g3ckdqt;
alter table SetCharacterDefinedTrait_focuses drop foreign key FK_jd7np5p8o3a5kglmjqrq81ogl;
alter table TraitChanges drop foreign key FK_9wqbr22xdk46h0hhshrotsv9k;
alter table TraitChanges drop foreign key FK_1soleuoltintdme7o8cj8qmis;
drop table if exists AuditEvent;
drop table if exists Backgrounds;
drop table if exists CharacterBackground_focuses;
drop table if exists CharacterSkill_focuses;
drop table if exists Distinctions;
drop table if exists Player;
drop table if exists PlayerCharacter;
drop table if exists PlayerCharacter_TraitChanges;
drop table if exists SetCharacterDefinedTrait_focuses;
drop table if exists Skills;
drop table if exists TraitChanges;
drop table if exists Troupe;
create table AuditEvent (id varchar(255) not null, audit_message varchar(255), audited_type varchar(255), audited_id varchar(255), timestamp datetime, primary key (id));
create table Backgrounds (id varchar(255) not null, rating integer, specialization varchar(255), background integer, primary key (id));
create table CharacterBackground_focuses (CharacterBackground_id varchar(255) not null, focuses varchar(255));
create table CharacterSkill_focuses (CharacterSkill_id varchar(255) not null, focuses varchar(255));
create table Distinctions (distinction_type varchar(31) not null, id varchar(255) not null, details varchar(255), ordinal integer, type varchar(255), primary key (id));
create table Player (id varchar(255) not null, deleted_at datetime, email varchar(255), name varchar(255), troupe_id varchar(255), primary key (id));
create table PlayerCharacter (id varchar(255) not null, deleted_at datetime, name varchar(255), player_id varchar(255), troupe_id varchar(255), primary key (id));
create table PlayerCharacter_TraitChanges (PlayerCharacter_id varchar(255) not null, traitChangeEvents_id varchar(255) not null, order_by integer not null, primary key (PlayerCharacter_id, order_by));
create table SetCharacterDefinedTrait_focuses (SetCharacterDefinedTrait_id varchar(255) not null, focuses varchar(255));
create table Skills (id varchar(255) not null, rating integer, specialization varchar(255), skill integer, primary key (id));
create table TraitChanges (trait_change_type varchar(31) not null, id varchar(255) not null, status integer, factory integer, ordinal integer, rating integer, specialization varchar(255), typeIdentifier varchar(255), child_id varchar(255), traitToRemove_id varchar(255), primary key (id));
create table Troupe (id varchar(255) not null, deleted_at datetime, name varchar(255), primary key (id));
alter table PlayerCharacter_TraitChanges add constraint UK_s5e9fv5uoth36s44agn30vqtt  unique (traitChangeEvents_id);
alter table CharacterBackground_focuses add constraint FK_gwyci7jpuwu0q3mucbf5q5rjq foreign key (CharacterBackground_id) references Backgrounds (id);
alter table CharacterSkill_focuses add constraint FK_m55thyly94po4rbmw03iay1u8 foreign key (CharacterSkill_id) references Skills (id);
alter table Player add constraint FK_ks4oof9guph2qvo7v6cqdiefx foreign key (troupe_id) references Troupe (id);
alter table PlayerCharacter add constraint FK_1wbxymbhm40bq5goo5laqy756 foreign key (player_id) references Player (id);
alter table PlayerCharacter add constraint FK_2tvilr6gkaifhe9fei568ij7b foreign key (troupe_id) references Troupe (id);
alter table PlayerCharacter_TraitChanges add constraint FK_s5e9fv5uoth36s44agn30vqtt foreign key (traitChangeEvents_id) references TraitChanges (id);
alter table PlayerCharacter_TraitChanges add constraint FK_ebyhdsyremvpge52v5g3ckdqt foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table SetCharacterDefinedTrait_focuses add constraint FK_jd7np5p8o3a5kglmjqrq81ogl foreign key (SetCharacterDefinedTrait_id) references TraitChanges (id);
alter table TraitChanges add constraint FK_9wqbr22xdk46h0hhshrotsv9k foreign key (child_id) references TraitChanges (id);
alter table TraitChanges add constraint FK_1soleuoltintdme7o8cj8qmis foreign key (traitToRemove_id) references TraitChanges (id);
